import  express  from "express";
import axios from "axios";
import bodyParser from "body-parser";
import 'dotenv/config';
import cors from "cors";

const app = express();
const port = 5000;
app.use(cors());
app.use(bodyParser.json())
const apiKey = process.env.RAPID_API_KEY;
const apiHost = process.env.API_HOST

// app.post("/api/newTab", async (req,res) => {
//     var date = req.body.date;
//     var league = req.body.league;
//     var sport = ""
//     if(req.body.league == "MLB"){
//         sport = "Baseball"
//     }
//     if(req.body.league == "NBA"){
//         sport = "Basketball"
//     }
//     if(req.body.league == "NFL"){
//         sport = "Football"
//     }
//     console.log(date,league,sport);
//     const options = {
//         method: 'GET',
//         url: 'https://thesportsdb.p.rapidapi.com/eventsday.php',
//         params: {
//           d: date,
//           l: league,
//           s: sport
//         },
//         headers: {
//           'X-RapidAPI-Key': apiKey,
//           'X-RapidAPI-Host': apiHost
//         }
//       };
// })

app.post("/api/initialGames", async (req,res) => {
    var dateFormat = "";
    var league = req.body.league;
    var sport = "";
    if(req.body.league == "MLB"){
    sport = "Baseball"
    }
    if(req.body.league == "NBA"){
        sport = "Basketball"
    }
    if(req.body.league == "NFL"){
        sport = "Football"
    }
    var day = req.body.day.toString();
    var month = ((req.body.month) + 1).toString();
    var year = req.body.year.toString();
    if(day.length <= 1){
        day = "0" + day;
    }
    if(month.length <= 1){
        month = "0" + month;
    }
    dateFormat = `${year}-${month}-${day}`
    console.log(dateFormat,league,sport)
    const options = {
        method: 'GET',
        url: 'https://thesportsdb.p.rapidapi.com/eventsday.php',
        params: {
          d: dateFormat,
          l: league,
          s: sport
        },
        headers: {
          'X-RapidAPI-Key': apiKey,
          'X-RapidAPI-Host': apiHost
        }
      };
    try {
        const response = await axios.request(options);
        // const response = {
        //     "events": [
        //         {
        //             "idEvent": "1815524",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7549",
        //             "strEvent": "Atlanta Falcons vs Green Bay Packers",
        //             "strEventAlternate": "Green Bay Packers @ Atlanta Falcons",
        //             "strFilename": "NFL 2023-09-17 Atlanta Falcons vs Green Bay Packers",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Atlanta Falcons",
        //             "strAwayTeam": "Green Bay Packers",
        //             "intHomeScore": "25",
        //             "intRound": "2",
        //             "intAwayScore": "24",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694970000",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "17:00:00",
        //             "strTimeLocal": "12:00:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "134942",
        //             "idAwayTeam": "134940",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Atlanta Falcons Quarter 1:<br>3 0 <br>Quarter 2<br>6 10 <br>Quarter 3<br>3 14 <br>Quarter 4<br>13 0 <br>Overtime<br> ",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "",
        //             "strSquare": "",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/mxhw4c1686337846.jpg",
        //             "strBanner": "",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "FT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         },
        //         {
        //             "idEvent": "1815525",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7550",
        //             "strEvent": "Buffalo Bills vs Las Vegas Raiders",
        //             "strEventAlternate": "Las Vegas Raiders @ Buffalo Bills",
        //             "strFilename": "NFL 2023-09-17 Buffalo Bills vs Las Vegas Raiders",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Buffalo Bills",
        //             "strAwayTeam": "Las Vegas Raiders",
        //             "intHomeScore": "38",
        //             "intRound": "2",
        //             "intAwayScore": "10",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694970000",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "17:00:00",
        //             "strTimeLocal": "12:00:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "134918",
        //             "idAwayTeam": "134932",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Buffalo Bills Quarter 1:<br>7 7 <br>Quarter 2<br>14 3 <br>Quarter 3<br>7 0 <br>Quarter 4<br>10 0 <br>Overtime<br> ",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "",
        //             "strSquare": "",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/wusxsd1686337848.jpg",
        //             "strBanner": "",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "FT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         },
        //         {
        //             "idEvent": "1815526",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7551",
        //             "strEvent": "Cincinnati Bengals vs Baltimore Ravens",
        //             "strEventAlternate": "Baltimore Ravens @ Cincinnati Bengals",
        //             "strFilename": "NFL 2023-09-17 Cincinnati Bengals vs Baltimore Ravens",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Cincinnati Bengals",
        //             "strAwayTeam": "Baltimore Ravens",
        //             "intHomeScore": "24",
        //             "intRound": "2",
        //             "intAwayScore": "27",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694970000",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "17:00:00",
        //             "strTimeLocal": "12:00:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "134923",
        //             "idAwayTeam": "134922",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Cincinnati Bengals Quarter 1:<br>0 7 <br>Quarter 2<br>10 6 <br>Quarter 3<br>7 7 <br>Quarter 4<br>7 7 <br>Overtime<br> ",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "https://www.thesportsdb.com/images/media/event/poster/omvjkx1674073305.jpg",
        //             "strSquare": "https://www.thesportsdb.com/images/media/event/square/ijdstv1674072468.jpg",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/xuy9jz1686337849.jpg",
        //             "strBanner": "https://www.thesportsdb.com/images/media/event/banner/bbzx9f1674073088.jpg",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "FT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         },
        //         {
        //             "idEvent": "1815527",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7552",
        //             "strEvent": "Detroit Lions vs Seattle Seahawks",
        //             "strEventAlternate": "Seattle Seahawks @ Detroit Lions",
        //             "strFilename": "NFL 2023-09-17 Detroit Lions vs Seattle Seahawks",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Detroit Lions",
        //             "strAwayTeam": "Seattle Seahawks",
        //             "intHomeScore": "31",
        //             "intRound": "2",
        //             "intAwayScore": "37",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694970000",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "17:00:00",
        //             "strTimeLocal": "12:00:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "134939",
        //             "idAwayTeam": "134949",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Detroit Lions Quarter 1:<br>7 7 <br>Quarter 2<br>7 0 <br>Quarter 3<br>7 10 <br>Quarter 4<br>10 14 <br>Overtime<br>0 6",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "https://www.thesportsdb.com/images/media/event/poster/u53d6r1659873793.jpg",
        //             "strSquare": "https://www.thesportsdb.com/images/media/event/square/2xj1li1659872597.jpg",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/mwo68f1686337852.jpg",
        //             "strBanner": "https://www.thesportsdb.com/images/media/event/banner/e66v6b1659875341.jpg",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "AOT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         },
        //         {
        //             "idEvent": "1815528",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7553",
        //             "strEvent": "Tennessee Titans vs Los Angeles Chargers",
        //             "strEventAlternate": "Los Angeles Chargers @ Tennessee Titans",
        //             "strFilename": "NFL 2023-09-17 Tennessee Titans vs Los Angeles Chargers",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Tennessee Titans",
        //             "strAwayTeam": "Los Angeles Chargers",
        //             "intHomeScore": "27",
        //             "intRound": "2",
        //             "intAwayScore": "24",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694970000",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "17:00:00",
        //             "strTimeLocal": "11:00:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "134929",
        //             "idAwayTeam": "135908",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Tennessee Titans Quarter 1:<br>0 3 <br>Quarter 2<br>10 11 <br>Quarter 3<br>7 0 <br>Quarter 4<br>7 10 <br>Overtime<br>3 0",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "",
        //             "strSquare": "",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/vef8m31686337854.jpg",
        //             "strBanner": "",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "AOT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         },
        //         {
        //             "idEvent": "1815529",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7554",
        //             "strEvent": "Tampa Bay Buccaneers vs Chicago Bears",
        //             "strEventAlternate": "Chicago Bears @ Tampa Bay Buccaneers",
        //             "strFilename": "NFL 2023-09-17 Tampa Bay Buccaneers vs Chicago Bears",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Tampa Bay Buccaneers",
        //             "strAwayTeam": "Chicago Bears",
        //             "intHomeScore": "27",
        //             "intRound": "2",
        //             "intAwayScore": "17",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694970000",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "17:00:00",
        //             "strTimeLocal": "12:00:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "134945",
        //             "idAwayTeam": "134938",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Tampa Bay Buccaneers Quarter 1:<br>3 7 <br>Quarter 2<br>10 3 <br>Quarter 3<br>7 0 <br>Quarter 4<br>7 7 <br>Overtime<br> ",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "",
        //             "strSquare": "",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/uqroy71686337856.jpg",
        //             "strBanner": "",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "FT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         },
        //         {
        //             "idEvent": "1815530",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7555",
        //             "strEvent": "Jacksonville Jaguars vs Kansas City Chiefs",
        //             "strEventAlternate": "Kansas City Chiefs @ Jacksonville Jaguars",
        //             "strFilename": "NFL 2023-09-17 Jacksonville Jaguars vs Kansas City Chiefs",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Jacksonville Jaguars",
        //             "strAwayTeam": "Kansas City Chiefs",
        //             "intHomeScore": "9",
        //             "intRound": "2",
        //             "intAwayScore": "17",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694970000",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "17:00:00",
        //             "strTimeLocal": "12:00:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "134928",
        //             "idAwayTeam": "134931",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Jacksonville Jaguars Quarter 1:<br>0 0 <br>Quarter 2<br>6 7 <br>Quarter 3<br>0 7 <br>Quarter 4<br>3 3 <br>Overtime<br> ",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "",
        //             "strSquare": "",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/cnw57h1686337858.jpg",
        //             "strBanner": "",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "FT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         },
        //         {
        //             "idEvent": "1815531",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7556",
        //             "strEvent": "Houston Texans vs Indianapolis Colts",
        //             "strEventAlternate": "Indianapolis Colts @ Houston Texans",
        //             "strFilename": "NFL 2023-09-17 Houston Texans vs Indianapolis Colts",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Houston Texans",
        //             "strAwayTeam": "Indianapolis Colts",
        //             "intHomeScore": "20",
        //             "intRound": "2",
        //             "intAwayScore": "31",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694970000",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "17:00:00",
        //             "strTimeLocal": "11:00:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "134926",
        //             "idAwayTeam": "134927",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Houston Texans Quarter 1:<br>7 14 <br>Quarter 2<br>3 14 <br>Quarter 3<br>0 3 <br>Quarter 4<br>10 0 <br>Overtime<br> ",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "https://www.thesportsdb.com/images/media/event/poster/rtcadc1659873775.jpg",
        //             "strSquare": "https://www.thesportsdb.com/images/media/event/square/nron2c1659872578.jpg",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/8hfxvf1686337860.jpg",
        //             "strBanner": "https://www.thesportsdb.com/images/media/event/banner/gygm561659875326.jpg",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "FT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         },
        //         {
        //             "idEvent": "1815532",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7557",
        //             "strEvent": "Los Angeles Rams vs San Francisco 49ers",
        //             "strEventAlternate": "San Francisco 49ers @ Los Angeles Rams",
        //             "strFilename": "NFL 2023-09-17 Los Angeles Rams vs San Francisco 49ers",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Los Angeles Rams",
        //             "strAwayTeam": "San Francisco 49ers",
        //             "intHomeScore": "23",
        //             "intRound": "2",
        //             "intAwayScore": "30",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694981100",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "20:05:00",
        //             "strTimeLocal": "12:05:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "135907",
        //             "idAwayTeam": "134948",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Los Angeles Rams Quarter 1:<br>3 7 <br>Quarter 2<br>14 10 <br>Quarter 3<br>0 3 <br>Quarter 4<br>6 10 <br>Overtime<br> ",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "https://www.thesportsdb.com/images/media/event/poster/c48pik1659873820.jpg",
        //             "strSquare": "https://www.thesportsdb.com/images/media/event/square/nyl9su1659872624.jpg",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/wucrm11686337861.jpg",
        //             "strBanner": "https://www.thesportsdb.com/images/media/event/banner/bzfn2y1659875362.jpg",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "FT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         },
        //         {
        //             "idEvent": "1815533",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7558",
        //             "strEvent": "Arizona Cardinals vs New York Giants",
        //             "strEventAlternate": "New York Giants @ Arizona Cardinals",
        //             "strFilename": "NFL 2023-09-17 Arizona Cardinals vs New York Giants",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Arizona Cardinals",
        //             "strAwayTeam": "New York Giants",
        //             "intHomeScore": "28",
        //             "intRound": "2",
        //             "intAwayScore": "31",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694981100",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "20:05:00",
        //             "strTimeLocal": "13:05:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "134946",
        //             "idAwayTeam": "134935",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Arizona Cardinals Quarter 1:<br>7 0 <br>Quarter 2<br>13 0 <br>Quarter 3<br>8 14 <br>Quarter 4<br>0 17 <br>Overtime<br> ",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "",
        //             "strSquare": "",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/xvog721686337863.jpg",
        //             "strBanner": "",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "FT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         },
        //         {
        //             "idEvent": "1815534",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7559",
        //             "strEvent": "Dallas Cowboys vs New York Jets",
        //             "strEventAlternate": "New York Jets @ Dallas Cowboys",
        //             "strFilename": "NFL 2023-09-17 Dallas Cowboys vs New York Jets",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Dallas Cowboys",
        //             "strAwayTeam": "New York Jets",
        //             "intHomeScore": "30",
        //             "intRound": "2",
        //             "intAwayScore": "10",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694982300",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "20:25:00",
        //             "strTimeLocal": "14:25:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "134934",
        //             "idAwayTeam": "134921",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Dallas Cowboys Quarter 1:<br>7 0 <br>Quarter 2<br>11 10 <br>Quarter 3<br>6 0 <br>Quarter 4<br>6 0 <br>Overtime<br> ",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "",
        //             "strSquare": "",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/wmyci01686337865.jpg",
        //             "strBanner": "",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "FT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         },
        //         {
        //             "idEvent": "1815535",
        //             "idSoccerXML": null,
        //             "idAPIfootball": "7560",
        //             "strEvent": "Denver Broncos vs Washington Commanders",
        //             "strEventAlternate": "Washington Commanders @ Denver Broncos",
        //             "strFilename": "NFL 2023-09-17 Denver Broncos vs Washington Commanders",
        //             "strSport": "American Football",
        //             "idLeague": "4391",
        //             "strLeague": "NFL",
        //             "strSeason": "2023",
        //             "strDescriptionEN": "",
        //             "strHomeTeam": "Denver Broncos",
        //             "strAwayTeam": "Washington Commanders",
        //             "intHomeScore": "33",
        //             "intRound": "2",
        //             "intAwayScore": "35",
        //             "intSpectators": null,
        //             "strOfficial": null,
        //             "strTimestamp": "1694982300",
        //             "dateEvent": "2023-09-17",
        //             "dateEventLocal": "2023-09-17",
        //             "strTime": "20:25:00",
        //             "strTimeLocal": "13:25:00",
        //             "strTVStation": null,
        //             "idHomeTeam": "134930",
        //             "idAwayTeam": "134937",
        //             "intScore": null,
        //             "intScoreVotes": null,
        //             "strResult": " Denver Broncos Quarter 1:<br>14 3 <br>Quarter 2<br>7 11 <br>Quarter 3<br>3 7 <br>Quarter 4<br>9 14 <br>Overtime<br> ",
        //             "strVenue": "",
        //             "strCountry": "United States",
        //             "strCity": "",
        //             "strPoster": "",
        //             "strSquare": "",
        //             "strFanart": null,
        //             "strThumb": "https://www.thesportsdb.com/images/media/event/thumb/8p6fm61686337866.jpg",
        //             "strBanner": "",
        //             "strMap": null,
        //             "strTweet1": "",
        //             "strTweet2": "",
        //             "strTweet3": "",
        //             "strVideo": "",
        //             "strStatus": "FT",
        //             "strPostponed": "no",
        //             "strLocked": "unlocked"
        //         }
        //     ]
        // }
        console.log("Games Sent to Client.")
        // console.log(response)
        res.json(response.data);
        
    }catch (error) {
        console.error(error);
        res.json(error);
    }
})

app.listen(port, () =>{
    console.log(`Api server has successfully started on port ${port}.`)
})